DATA_TYPES = {
    'AutoField':         'serial',
    'BooleanField':      'smallint',
    'CharField':         'varchar(%(maxlength)s)',
    'CommaSeparatedIntegerField': 'varchar(%(maxlength)s)',
    'DateField':         'date',
    'DateTimeField':     'datetime YEAR TO FRACTION(5)',
    'FileField':         'varchar(100)',
    'FilePathField':     'varchar(100)',
    'FloatField':        'decimal(%(max_digits)s, %(decimal_places)s)',
    'ImageField':        'varchar(100)',
    'IntegerField':      'int',
    'IPAddressField':    'char(15)',
    'ManyToManyField':   None,
    'NullBooleanField':  'smallint',
    'OneToOneField':     'int',
    'PhoneNumberField':  'varchar(20)',
    'PositiveIntegerField': 'int',
    'PositiveSmallIntegerField': 'smallint',
    'SlugField':         'varchar(%(maxlength)s)',
    'SmallIntegerField': 'smallint',
    'TextField':         'CHAR(16000)',
    'TimeField':         'datetime HOUR TO SECOND',
    'URLField':          'varchar(200)',
    'USStateField':      'varchar(2)',
}
